# Generated by Django 2.0.5 on 2018-08-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocked', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='textWidth',
        ),
        migrations.AddField(
            model_name='design',
            name='textColor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
